#
# Blog Settings
#

# Jekyll Settings
destination: ./_site
pygments: true
paginate: 6
paginate_path: /page/:num
permalink: /:year/:month/:day/:title/
baseurl: ""
#lsi: true

# Build settings
markdown: rdiscount
excerpt_separator: "<!-- more -->"
    
  
# Disqus Comments
disqus_short_name: barretlee
disqus_show_comment_count: true

# site
title: Sean Lou
url: http://www.lxj.name
repo: http://github.com/lxj.github.com
feed: /atom.xml
  
# color scheme
highlight: light

# author
author:
  name: Sean Lou
  email: louxiaojian@gmail.com
  info: <a href="http://www.lxj.name">SeanLou</a>

css:
  - /assets/css/lxj.css

js:
  - /assets/js/lxj.js
  
img: /assets/img
 
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - Gruntfile.js
  - package.json
  - CNAME
  - Website.tmproj
  - src
  - _site
    
# Plugins
gems:
  - jekyll-archives
  - jekyll-redirect-from

  
# jekyll-archives
jekyll-archives:
  enabled: []
  layouts:
    year: 'archive'
    month: 'archive'
    day: 'archive'
    tag: 'archive'
    category: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
    
# jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all    
  
  
