#
# Blog Settings
#

# Jekyll Settings
destination: ./_site
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: barretlee
disqus_show_comment_count: true

# site
title: BarretLee's Blog
url: http://www.lxj.name
repo: http://github.com/lxj.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: Sean Lou
author_email: louxiaojian@gmail.com
author_info: <a href="http://www.lxj.name">SeanLou</a>

tags:
	url: /tags/
	title_prefix: "blog - tag: "
	layout: tag.html

categories:
	url: /categories/
	title_prefix: "blog - categories: "
	layout: javascript.html