#
# Blog Settings
#

# Jekyll Settings
destination: ./_site
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page/:num
permalink: /:year/:month/:day/:title/
baseurl: ""
#lsi: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - vendor
  
# Disqus Comments
disqus_short_name: barretlee
disqus_show_comment_count: true

# site
title: Sean Lou
url: http://www.lxj.name
repo: http://github.com/lxj.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: Sean Lou
author_email: louxiaojian@gmail.com
author_info: <a href="http://www.lxj.name">SeanLou</a>

# Plugins
gems:
  - jekyll-archives

  
# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
